version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
      POSTGRES_HOST: db
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT_EXT: "5432"
      PORT: "3001"
    command: sh -c "npm run migration:run && npm run start:prod"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data 

volumes:
  db-data:
    driver: local